"""Add account action tokens"""
from alembic import op
import sqlalchemy as sa

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_action_tokens_expires_at'), 'action_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_action_tokens_user_id'), 'action_tokens', ['user_id'], unique=False)
    op.create_index('ix_action_tokens_user_purpose', 'action_tokens', ['user_id', 'purpose'], unique=False)
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_index('ix_action_tokens_user_purpose', table_name='action_tokens')
    op.drop_index(op.f('ix_action_tokens_user_id'), table_name='action_tokens')
    op.drop_index(op.f('ix_action_tokens_expires_at'), table_name='action_tokens')
    op.drop_table('action_tokens')
    # ### end Alembic commands ###
